#pragma once
#include <raylib.h>
#include <cstring>

// Pixel-art sprites as strings. '.' is transparent. Outlines and rim light are added
// automatically when the sprite is first drawn (see rig.cpp), so the art here is fill only.
// 'a'/'A' are a dynamic tint colour (light/dark).

inline Color paletteColor(char ch, Color armour)
{
    switch (ch)
    {
    case 'k': return {28, 22, 30, 255};
    case 'x': return {0, 0, 0, 255};
    case 's': return {255, 209, 156, 255};
    case 'S': return {229, 147, 99, 255};
    case 'c': return {44, 64, 140, 255};
    case 'C': return {26, 38, 92, 255};
    case 'b': return {131, 88, 56, 255};
    case 'B': return {92, 58, 36, 255};
    case 'g': return {98, 162, 62, 255};
    case 'G': return {56, 110, 44, 255};
    case 'q': return {156, 210, 98, 255};
    case 'r': return {214, 52, 52, 255};
    case 'R': return {140, 26, 34, 255};
    case 'w': return {236, 232, 214, 255};
    case 'W': return {176, 170, 152, 255};
    case 'm': return {182, 190, 204, 255};
    case 'M': return {104, 112, 130, 255};
    case 'L': return {226, 232, 242, 255};
    case 'v': return {26, 26, 38, 255};
    case 'p': return {124, 58, 156, 255};
    case 'P': return {70, 30, 98, 255};
    case 'y': return {242, 202, 62, 255};
    case 'Y': return {255, 244, 150, 255};
    case 'd': return {215, 184, 77, 255};
    case 'D': return {181, 154, 61, 255};
    case 'o': return {242, 128, 36, 255};
    case 'O': return {180, 62, 22, 255};
    case 'i': return {186, 228, 255, 210};
    case 'I': return {110, 168, 222, 210};
    case 'e': return {255, 255, 255, 255};
    case 'F': return {241, 240, 253, 255};
    case 'u': return {40, 93, 170, 255};
    case 'n': return {132, 128, 122, 255};
    case 'N': return {88, 84, 82, 255};
    case 'l': return {170, 255, 140, 230};
    case 'E': return {146, 153, 164, 255};
    case 'f': return {64, 64, 62, 255};
    case 'j': return {218, 217, 204, 255};
    case 'J': return {180, 180, 174, 255};
    case 'h': return {105, 72, 58, 255};
    case 'H': return {145, 100, 81, 255};
    case 'a': return armour;
    case 'A': return {(unsigned char)(armour.r * 0.62f), (unsigned char)(armour.g * 0.62f), (unsigned char)(armour.b * 0.62f), 255};
    default: return {255, 0, 255, 255};
    }
}

struct Sprite
{
    const char* const* rows;
    int h;
};

#define SPRITE(name, ...)                                  \
    static const char* const name##_rows[] = {__VA_ARGS__}; \
    static const Sprite name = {name##_rows, (int)(sizeof(name##_rows) / sizeof(name##_rows[0]))};

// ---------------------------------------------------------------- creatures (chibi, facing right)

SPRITE(SPR_GOBLIN_A,
       "....gggg....",
       "G..gqqqgg..G",
       "GgggqqqqgggG",
       ".GgYkqqYkgG.",
       "..gqqqqqqg..",
       "..gqwRwRqg..",
       "...gggggg...",
       "....gggg....",
       "...BbbbbB...",
       "..gBbbybBg..",
       "..gBbbbbBg..",
       "..qBBBBBBq..",
       "....BbbB....",
       "....G..G....",
       "....G..G....",
       "...bb..bb...")
SPRITE(SPR_GOBLIN_B,
       "....gggg....",
       "G..gqqqgg..G",
       "GgggqqqqgggG",
       ".GgYkqqYkgG.",
       "..gqqqqqqg..",
       "..gqwRwRqg..",
       "...gggggg...",
       "....gggg....",
       "...BbbbbB...",
       "..gBbbybBg..",
       "..gBbbbbBg..",
       "..qBBBBBBq..",
       "....BbbB....",
       "...G....G...",
       "...G....G...",
       "..bb....bb..")
SPRITE(SPR_BOMBER,
       "....RRRR....",
       "G..RrrrRR..G",
       "GggRRRRRRggG",
       ".GgYkqqYkgG.",
       "..gqqqqqqg..",
       "..gqwRwRqg.Y",
       "...gggggg.k.",
       "....gggg.kkk",
       "...BbbbbBkkk",
       "..gBbbybBgk.",
       "..gBbbbbBg..",
       "..qBBBBBBq..",
       "....BbbB....",
       "....G..G....",
       "....G..G....",
       "...bb..bb...")
SPRITE(SPR_SKELETON_A,
       "....wwww....",
       "...wwwwww...",
       "...wkwwkW...",
       "...wrwwrW...",
       "...wwwwwW...",
       "....wkwkW...",
       ".....WW.....",
       "....wwww....",
       "...w.ww.w...",
       "..w.wwww.w..",
       "..w.w..w.w..",
       "..W.wwww.W..",
       "..w..WW..w..",
       ".....ww.....",
       "....wwww....",
       "....w..w....",
       "....w..w....",
       "....W..W....",
       "....w..w....",
       "....w..w....",
       "....W..W....",
       "...ww..ww...")
SPRITE(SPR_SKELETON_B,
       "....wwww....",
       "...wwwwww...",
       "...wkwwkW...",
       "...wrwwrW...",
       "...wwwwwW...",
       "....wkwkW...",
       ".....WW.....",
       "....wwww....",
       "...w.ww.w...",
       "..w.wwww.w..",
       "..w.w..w.w..",
       "..W.wwww.W..",
       "..w..WW..w..",
       ".....ww.....",
       "....wwww....",
       "...w....w...",
       "...w....w...",
       "...W....W...",
       "..w......w..",
       "..w......w..",
       "..W......W..",
       ".ww......ww.")
SPRITE(SPR_ARCHER,
       "....PPPP......",
       "...PppppP.....",
       "...PwwwwP.b...",
       "...PkwkwP.bb..",
       "...PrwrwP..b..",
       "...PwwwwP..b..",
       "....PwkP...b..",
       "...PPWWPP..b..",
       "..PpwwwwpP.b..",
       "..Pw.ww.wwwwb.",
       "..P.wwww...b..",
       "..P.w..w...b..",
       "..PpwwwwpP.b..",
       "...PpWWpP.b...",
       "....wwww......",
       "....w..w......",
       "....w..w......",
       "....W..W......",
       "....w..w......",
       "....w..w......",
       "....W..W......",
       "...ww..ww.....")
SPRITE(SPR_BAT_A,
       "PP............PP",
       "pPP..........PPp",
       "pPPP.P....P.PPPp",
       ".pPPPPPPPPPPPPp.",
       "..pPPPrPPrPPPp..",
       "....PPPwwPPP....",
       ".....PPPPPP.....",
       "......P..P......")
SPRITE(SPR_BAT_B,
       "................",
       "................",
       ".....P....P.....",
       "....PPPPPPPP....",
       "..pPPPrPPrPPPp..",
       ".pPPPPPwwPPPPPp.",
       "pPP...PPPP...PPp",
       "PP....P..P....PP")
SPRITE(SPR_SLIME,
       "......llll......",
       "....llqqqqll....",
       "...lqqggggqql...",
       "..lqgggggggggl..",
       ".lggFkggggFkggl.",
       ".lggFkggggFkggl.",
       "lggggggggggggggl",
       "lgggggwRRwgggggl",
       "lGggggggggggggGl",
       ".lGGgggggggggGl.",
       "..lGGGGGGGGGGl..",
       "...llllllllll...")
SPRITE(SPR_CULTIST,
       ".....PP.....",
       "....PppP....",
       "...PppppP...",
       "...PPxxxP...",
       "...PxYxYP...",
       "...PPxxxP...",
       "....PppP....",
       "...PpppppP..",
       "..PppyyppP..",
       "..PpppyppPs.",
       "..sPpppppP..",
       "...PpppppP..",
       "...PpPppPP..",
       "...PppppppP.",
       "..PpPppppPP.",
       "..PppppppppP",
       "..PpPpppPppP",
       ".PppppppppPP",
       ".PpPppppPppP",
       ".PPPPPPPPPPP",
       "...kk...kk..",
       "...kk...kk..")
SPRITE(SPR_KNIGHT_A,
       "......rr......",
       ".....rRrr.....",
       ".....mmmm.....",
       "....mLmmmM....",
       "....mvvvvM....",
       "....mmmvmM....",
       "....MmmmMM....",
       ".....MMMM.....",
       "...LmmmmmmM...",
       "..LmmmyymmmM..",
       "..mmMmmmmMmM..",
       "..mmMmmmmMmM..",
       "..MM.mmmm.MM..",
       "..mm.mMMm.mm..",
       "..LL.mmmm.LL..",
       ".....MmmM.....",
       ".....mm.mm....",
       ".....mm.mm....",
       ".....mm.mm....",
       ".....MM.MM....",
       ".....mm.mm....",
       ".....mm.mm....",
       ".....MM.MM....",
       "....MMM.MMM...")
SPRITE(SPR_KNIGHT_B,
       "......rr......",
       ".....rRrr.....",
       ".....mmmm.....",
       "....mLmmmM....",
       "....mvvvvM....",
       "....mmmvmM....",
       "....MmmmMM....",
       ".....MMMM.....",
       "...LmmmmmmM...",
       "..LmmmyymmmM..",
       "..mmMmmmmMmM..",
       "..mmMmmmmMmM..",
       "..MM.mmmm.MM..",
       "..mm.mMMm.mm..",
       "..LL.mmmm.LL..",
       ".....MmmM.....",
       "....mm...mm...",
       "....mm...mm...",
       "....mm...mm...",
       "...MM.....MM..",
       "...mm.....mm..",
       "...mm.....mm..",
       "...MM.....MM..",
       "..MMM.....MMM.")
SPRITE(SPR_IMP,
       "O..........O",
       "OO..oooo..OO",
       ".OOoooooooO.",
       "..oooooooo..",
       "..oYkooYko..",
       "..oooooooo..",
       "...owwwwo...",
       "....oooo....",
       "..OooooooO..",
       ".O.oooooo.O.",
       "...oOooOo...",
       "...oo..oo...",
       "..OO....OO..")
SPRITE(SPR_WRAITH,
       "....iiiiii....",
       "...iiiiiiii...",
       "..iiiiiiiiii..",
       "..iikkiikkii..",
       "..iikeiikeii..",
       "..iiiiiiiiii..",
       "...iikkkkii...",
       "....iiiiii....",
       "..iIiiiiiiIi..",
       ".iIiiiiiiiiIi.",
       "iI.iiiiiiii.Ii",
       "i..iiiIIiii..i",
       "...iiiiiiii...",
       "...iIiiiiIi...",
       "...iiiiiiii...",
       "..iiIiiiiIii..",
       "..iIiiiIiiIi..",
       ".iI.iiI.iI.Ii.",
       ".i..iI...iI.i.",
       "......i....i..")
SPRITE(SPR_GOLEM,
       "......nnnnnnnn......",
       ".....nNnnnnnnNn.....",
       "....nnnnnnnnnnnn....",
       "....nnYYnnnnYYnn....",
       "....nnnnnnnnnnnn....",
       "....nNnnnNNnnnNn....",
       ".....nnnnnnnnnn.....",
       "..nnnnnnnnnnnnnnnn..",
       ".nnNnnnnnnnnnnnnNnn.",
       "nnNNnnnnGGnnnnnnNNnn",
       "nnnnnnnnnnnnnnnnnnnn",
       "nNnn.nnnnnnnnnn.nnNn",
       "nnnn.nnnNnnNnnn.nnnn",
       "nnnn.nnnnnnnnnn.nnnn",
       ".nn..nnnnnnnnnn..nn.",
       "nnnn.nnNnnnnNnn.nnnn",
       "NNNN.nnnnnnnnnn.NNNN",
       ".....nnnnnnnnnn.....",
       ".....nnnn..nnnn.....",
       ".....nnnn..nnnn.....",
       ".....nnNn..nNnn.....",
       "....nnnnn..nnnnn....",
       "....NNNNN..NNNNN....")
SPRITE(SPR_BLACKKNIGHT,
       "...M..............M...",
       "...MM............MM...",
       "....MM..kkkkkk..MM....",
       ".....MkkMMMMMMkkM.....",
       "......kMMMMMMMMk......",
       ".....kMMMMMMMMMMk.....",
       ".....kMMrrMMMrrMk.....",
       ".....kMMMMMMMMMMk.....",
       ".....kMvkvkvkvkMk.....",
       "......kMMMMMMMMk......",
       ".......kkMMMMkk.......",
       "...kkkkMMMMMMMMkkkk...",
       "..kMMMMMMMMMMMMMMMMk..",
       ".kMMmMMMMMrrMMMMMmMMk.",
       ".kMMMMMMMMrrMMMMMMMMk.",
       ".kMMkMMMMMMMMMMMMkMMk.",
       ".kMMkMMMMMMMMMMMMkMMk.",
       ".kmMkMMMMyyyyMMMMkMmk.",
       ".kMMkkMMMMMMMMMMkkMMk.",
       "..kk.kMMMMMMMMMMk.kk..",
       ".....kMMMMkkMMMMk.....",
       ".....kMMMk..kMMMk.....",
       ".....kMMMk..kMMMk.....",
       ".....kMMMk..kMMMk.....",
       ".....kMMMk..kMMMk.....",
       "....kMMMMk..kMMMMk....",
       "....kkkkkk..kkkkkk....")
SPRITE(SPR_LICH,
       "..y.y.yyyy.y.y....",
       "..yyyyyyyyyyyy....",
       "...wwwwwwwwww.....",
       "..wwwwwwwwwwww....",
       "..wwkkwwwwkkww....",
       "..wwkYwwwwkYww....",
       "..wwwwwwwwwwww....",
       "...wwwwkkwwww.....",
       "...wkwkwkwkww.....",
       "....wwwwwwww....Y.",
       "..PPPPpwwpPPPP..b.",
       ".PPpppppppppppP.b.",
       "PPpPpppyypppPpPPb.",
       "Pp.PppppppppP.pPb.",
       "w..PpppppppP..wwb.",
       "...PppppppppP...b.",
       "...PpppppppppP..b.",
       "..PppPpppppPpP..b.",
       "..PpppppppppppP.b.",
       "..PpPpppppppPpP.b.",
       ".PppppppppppppPPb.",
       ".PpPppppppppPppPb.",
       "PPPPPPPPPPPPPPPPb.")

SPRITE(SPR_WOLF_A,
       "..............nn..",
       ".............nnnn.",
       "n...........nnYnnn",
       ".n..nnnnnnnnnnnnkw",
       "..nnnnnnnnnnnnnNN.",
       "..nnnnnnnnnnnnN...",
       "..nNnnnnnnnnnnN...",
       "...nn.nN...nn.n...",
       "...n..n.....n..n..",
       "...n..n.....n..n..",
       "..NN.NN....NN.NN..")
SPRITE(SPR_WOLF_B,
       "..............nn..",
       ".............nnnn.",
       "n...........nnYnnn",
       ".n..nnnnnnnnnnnnkw",
       "..nnnnnnnnnnnnnNN.",
       "..nnnnnnnnnnnnN...",
       "..nNnnnnnnnnnnN...",
       "...nn.nN...nn.n...",
       "....nn.n...n.n....",
       "....n..n..n..n....",
       "...NN.NN.NN.NN....")
SPRITE(SPR_REDCAP,
       "...RRRR...",
       "..RrrrRR..",
       ".RRRRRRRR.",
       "..sSssss..",
       "..sYkssk..",
       "..sssssS..",
       "..sSwwwS..",
       "...ssss...",
       "..bbbbbb..",
       ".sbBbbBbs.",
       ".sbbybbbs.",
       "..bbbbbb..",
       "...BB.BB..",
       "...mm.mm..",
       "...mm.mm..",
       "..MMM.MMM.")
SPRITE(SPR_DRAUGR,
       "...M....M...",
       "...mM..Mm...",
       "....mmmm....",
       "...mmmmmm...",
       "...IYIIYI...",
       "...IIIIII...",
       "...WWWWWW...",
       "....WWWW....",
       "..NNNNNNNN..",
       ".INnnnnnnNI.",
       ".INnnbbnnNI.",
       ".INnnnnnnNI.",
       ".INNNyyNNNI.",
       "..NnnnnnnN..",
       "..NnnnnnnN..",
       "...nnnnnn...",
       "...nn..nn...",
       "...nn..nn...",
       "...NN..NN...",
       "...nn..nn...",
       "...nn..nn...",
       "...NN..NN...",
       "..bbb..bbb..")
SPRITE(SPR_TROLL,
       ".......GGGGGG.........",
       "......GgggggGG........",
       ".....GgggggggG........",
       ".....GgYggYggG........",
       ".....GgggggggGG.......",
       "......GgwggwgG........",
       "......GGgggggG........",
       "...GGGGGgggGGGGG......",
       "..GggggggggggggggG....",
       ".GggGgggggggggGgggG...",
       ".GggGggggbbggggGgggG..",
       ".GggGgggbbbbgggGgggGb.",
       ".GgGGgggggggggggGgGGbb",
       "..gg.GgggggggggG.gg.bb",
       "..gg.GgggggggggG.gg.bb",
       "..GG.GgggggggggG.GG.b.",
       ".....GgggggggggG....b.",
       ".....BBBBBBBBBBB......",
       ".....GggggGgggggG.....",
       ".....GgggG.GggggG.....",
       ".....GgggG..GgggG.....",
       ".....GgggG..GgggG.....",
       ".....GgggG..GgggG.....",
       "....GGgggG..GgggGG....",
       "....GgggGG..GGgggG....",
       "...GgggggG..GgggggG...",
       "...GGGGGGG..GGGGGGG...")
SPRITE(SPR_BANSHEE,
       "....wwwwww....",
       "...wwwwwwww...",
       "..wwiiiiiiww..",
       "..wwikiikiww..",
       "..wwiiiiiiww..",
       "..wwiikkiiww..",
       "..wwwikkiwww..",
       "..ww.iiii.ww..",
       ".wwPPPPPPPPww.",
       ".wiPpppppppiw.",
       "iw.PppppppP.wi",
       "i..PppppppP..i",
       "...PppppppP...",
       "...PpPpppPp...",
       "..PppppppppP..",
       "..PpppPppppP..",
       "..PpPpppPppP..",
       ".PppppppppppP.",
       ".PpPpPppPpPpP.",
       "..P.Pp.P.pP...",
       "..P..p.P..P...",
       "......P.......")
SPRITE(SPR_KELPIE,
       "................g...",
       "...............ggG..",
       "..............CCCCg.",
       ".............CCkCCCg",
       "............CCCCCCCc",
       "...........CCCgCCc..",
       ".CCCCCCCCCCCCCgCC...",
       "CCCCCCCCCCCCCCgC....",
       "CcCCCCCCCCCCCCC.....",
       ".CCCCCCCCCCCCCC.....",
       "..CC.CC....CC.CC....",
       "..C..C.....C..C.....",
       "..C..C.....C..C.....",
       ".CC.CC....CC.CC.....")
SPRITE(SPR_GUARD_A,
       "....mmmm....",
       "...LmmmmM...",
       "..MMMMMMMM..",
       "...ssssS....",
       "...sFusS....",
       "...sssss....",
       "....sSs.....",
       "...RRRRRR.m.",
       "..RRrrrrRRm.",
       "..sRrrrrRsm.",
       "..sRryyrR.m.",
       "...RrrrrR.m.",
       "...RRRRRR.m.",
       "...bbbbbb.m.",
       "...EE..EE.m.",
       "...EE..EE.m.",
       "...EE..EE.b.",
       "...EE..EE.b.",
       "...EE..EE...",
       "...EE..EE...",
       "...EE..EE...",
       "...bb..bb...",
       "..bbb..bbb..")
SPRITE(SPR_GUARD_B,
       "....mmmm....",
       "...LmmmmM...",
       "..MMMMMMMM..",
       "...ssssS....",
       "...sFusS....",
       "...sssss....",
       "....sSs.....",
       "...RRRRRR.m.",
       "..RRrrrrRRm.",
       "..sRrrrrRsm.",
       "..sRryyrR.m.",
       "...RrrrrR.m.",
       "...RRRRRR.m.",
       "...bbbbbb.m.",
       "..EE....EEm.",
       "..EE....EEm.",
       "..EE....EEb.",
       ".EE......EE.",
       ".EE......EE.",
       ".EE......EE.",
       ".EE......EE.",
       ".bb......bb.",
       "bbb......bbb")

SPRITE(SPR_MERCHANT,
       "..hHHh....",
       ".hhHHHh...",
       "hhhSssH...",
       "hhSsFus...",
       "hhSssss...",
       ".hSssSs...",
       "..hSss....",
       "..jjjjj...",
       ".jjjjjjj..",
       "sjwwwwwjs.",
       "sjwwwwwjs.",
       ".jwwwwwj..",
       ".bwwwwwb..",
       ".bbbbbbb..",
       "..EE.EE...",
       "..EE.EE...",
       "..EE.EE...",
       "..bb.bb...",
       ".bbb.bbb..")

// ---------------------------------------------------------------- objects
SPRITE(SPR_CHEST,
       ".bbbbbbb.",
       "bBBBBBBBb",
       "bbbbybbbb",
       "bBBByBBBb",
       "bbbbbbbbb",
       "BBBBBBBBB")
SPRITE(SPR_CHEST_OPEN,
       ".bbbbbbb.",
       "b.......b",
       "byyYyyYyb",
       "bBBBBBBBb",
       "bbbbbbbbb",
       "BBBBBBBBB")
SPRITE(SPR_ANVIL,
       "mmmmmmmmmm.",
       ".Mmmmmmmmmm",
       "...mmmmm...",
       "....MMM....",
       "...MMMMM...",
       "..NNNNNNN..")
SPRITE(SPR_SHRINE,
       "...nnn...",
       "..nNnNn..",
       "...nnn...",
       "...nNn...",
       "...nnn...",
       "...nNn...",
       "...nnn...",
       "...nNn...",
       "..nnnnn..",
       ".nNnnnNn.",
       "nnnnnnnnn",
       "NNNNNNNNN")
SPRITE(SPR_HEART,
       ".r.r.",
       "rrrrr",
       ".rrr.",
       "..r..")
SPRITE(SPR_POTION,
       ".bb.",
       ".mm.",
       "rrrr",
       "rRrr",
       ".rr.")
SPRITE(SPR_SCROLL,
       "wwwww",
       "WaaaW",
       "wwwww",
       "WwwwW")

// Draw a sprite at integer position (render-texture space). flip mirrors horizontally.
inline void drawSprite(const Sprite& s, float fx, float fy, bool flip, Color armour = WHITE, Color flash = BLANK, float alpha = 1.0f)
{
    int x = (int)fx, y = (int)fy;
    for (int j = 0; j < s.h; j++)
    {
        const char* row = s.rows[j];
        int w = (int)std::strlen(row);
        for (int i = 0; i < w; i++)
        {
            char ch = row[i];
            if (ch == '.')
                continue;
            Color c = paletteColor(ch, armour);
            if (flash.a)
                c = flash;
            c.a = (unsigned char)(c.a * alpha);
            DrawRectangle(x + (flip ? w - 1 - i : i), y + j, 1, 1, c);
        }
    }
}

inline int spriteWidth(const Sprite& s) { return (int)std::strlen(s.rows[0]); }
