# The Norse longship. The hull is the user's own pixel art (reference/ship_hull_user.png, cropped to its 130x57 box and used at 1:1,
# one pixel = one sand cell); everything else - the mast with yard and pennant, the sun-bleached wreck - is painted here to match it.
# Rows from HULL_WL down are under water, so they are blue-shifted, darker toward the keel. The game draws the live sail.
#   python tools/ship.py emit > sprites_ship.h     (hull, mast, wreck hull, wreck mast)
#   python tools/ship.py preview <dir>             (4x sheets)
import math, sys, os
import numpy as np
from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, '..', 'reference', 'ship_hull_user.png')
CROP = (5, 8, 135, 65)
HULL_CX, HULL_WL = 65, 47          # hull centre column; waterline row (mirrored in game.h as LS_CX / LS_KEEL)
MW, MH, MCX = 104, 132, 52         # mast image (mirrored as LM_CX / LM_H)

PAL = {'k': (30, 16, 24), 'o0': (62, 30, 28), 'o1': (104, 52, 32), 'o2': (150, 80, 40), 'o3': (190, 108, 52),
       'rd': (180, 48, 44), 'cr': (236, 222, 186), 'ye': (236, 190, 70), 'wt': (252, 250, 240), 'tar': (40, 26, 30),
       'rope': (150, 112, 70), 'gs': (40, 84, 56)}


def pt(im, x, y, c):
    if 0 <= x < im.width and 0 <= y < im.height: im.putpixel((int(x), int(y)), PAL[c] + (255,))


def disc(im, cx, cy, r, c):
    for y in range(int(cy - r - 1), int(cy + r + 2)):
        for x in range(int(cx - r - 1), int(cx + r + 2)):
            if (x - cx) ** 2 + (y - cy) ** 2 <= r * r: pt(im, x, y, c)


def build_hull():
    a = np.array(Image.open(SRC).convert('RGBA').crop(CROP)).astype(float)
    for y in range(HULL_WL, a.shape[0]):                    # under water: blue-shifted, deeper = darker and bluer
        t = min(1.0, 0.35 + 0.65 * (y - HULL_WL) / (a.shape[0] - HULL_WL))
        a[y, :, :3] = a[y, :, :3] * (1 - 0.55 * t) + np.array([18, 52, 96]) * 0.55 * t
    return Image.fromarray(a.astype(np.uint8))


def build_mast(broken):
    im = Image.new('RGBA', (MW, MH))
    top = 64 if broken else 6
    for y in range(top, MH):
        for x in (MCX - 2, MCX - 1, MCX, MCX + 1):
            pt(im, x, y, ('o1' if x == MCX - 2 else 'o2' if x < MCX + 1 else 'o0') if not broken else ('o0' if x == MCX + 1 else 'o1'))
        pt(im, MCX - 3, y, 'k'); pt(im, MCX + 2, y, 'k')
    if not broken:
        for x in range(2, MW - 2):                           # the yard, curving up a little at both tips
            y = 12 - int(3 * (abs(x - MCX) / (MCX - 2)) ** 3)
            pt(im, x, y - 1, 'k'); pt(im, x, y, 'o3'); pt(im, x, y + 1, 'o2'); pt(im, x, y + 2, 'o0'); pt(im, x, y + 3, 'k')
        disc(im, MCX, 12, 3.2, 'tar'); disc(im, MCX - 1, 11, 1.2, 'rope')
        for i in range(30):                                  # the pennant
            for k in range(0, 8 - i // 5):
                pt(im, MCX + 2 + i, 2 + k + 1 + math.sin(i * 0.5), 'rd' if k else 'k')
        for i in range(14): pt(im, MCX + 8 + i, 6, 'cr')
        disc(im, MCX, 5, 3, 'ye'); pt(im, MCX - 1, 4, 'wt')
    else:
        for k in range(5): pt(im, MCX - 2 + k, top - 1 - (k * 3) % 4, 'o1')
    return im


def weather(im):
    """Beached wreck: sun-bleached, grey-green with rot and weed."""
    a = np.array(im).astype(float)
    m = a[..., 3] > 0
    grey = a[..., :3].mean(-1, keepdims=True)
    a[..., :3] = (a[..., :3] * 0.5 + grey * 0.5) * np.array([0.9, 0.92, 0.8])
    for y, x in zip(*np.nonzero(m)):
        h = math.sin(x * 12.9898 + y * 78.233) * 43758.5453 % 1
        if h > 0.93: a[y, x, :3] = PAL['gs']
        elif h < 0.04: a[y, x, :3] = PAL['tar']
    return Image.fromarray(a.astype(np.uint8))


def wreck_hull():
    d = np.array(weather(build_hull()))
    for x in range(35, 50): d[:14, x, 3] = 0                 # the rail broken away
    for hx in (22, 50, 84):                                  # sprung planks: gaps in the side
        for y in range(18, 40):
            for x in range(hx, hx + 3 + (y * 7) % 3): d[y, x, 3] = 0
    return Image.fromarray(d)


def quantize(imgs, maxc=86):
    from collections import Counter
    cnt = Counter()
    for im in imgs:
        a = im.reshape(-1, 4)
        for c in map(tuple, a[a[:, 3] > 0][:, :3]): cnt[c] += 1
    cols = [c for c, _ in cnt.most_common()]
    keep = cols[:maxc]
    keepa = np.array(keep, float)
    cmap = {}
    for c in cols: cmap[c] = c if c in keep else keep[int(np.argmin(((keepa - np.array(c, float)) ** 2).sum(1)))]
    return keep, cmap


ALPHA = [ch for ch in "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz!#$%&()*+,-/:;<=>@[]^_{|}~" if ch not in '?']


def emit(parts):
    keep, cmap = quantize([p for _, p in parts])
    idx = {c: ALPHA[i] for i, c in enumerate(keep)}
    out = ['// Generated by tools/ship.py - edit there, then: python tools/ship.py emit > sprites_ship.h', '#pragma once', '#include <raylib.h>', '',
           '// The longship at one pixel per sand cell. Row characters index SHIP_ALPHABET; \'.\' is transparent.',
           'static const char SHIP_ALPHABET[] = "%s";' % ''.join(ALPHA[:len(keep)]),
           'static const Color SHIP_PAL[] = {%s};' % ', '.join('{%d,%d,%d,255}' % c for c in keep), '']
    for name, im in parts:
        h, w = im.shape[:2]
        out.append('static const int %s_W = %d, %s_H = %d;' % (name, w, name, h))
        out.append('static const char* const %s[] = {' % name)
        for y in range(h):
            out.append('"%s",' % ''.join('.' if im[y, x, 3] == 0 else idx[cmap[tuple(im[y, x, :3])]] for x in range(w)))
        out.append('};')
    return '\n'.join(out)


def main():
    parts = [('SHIP_HULL', np.array(build_hull())), ('SHIP_MAST', np.array(build_mast(False))),
             ('SHIP_WRECK_HULL', np.array(wreck_hull())), ('SHIP_WRECK_MAST', np.array(weather(build_mast(True))))]
    if len(sys.argv) > 1 and sys.argv[1] == 'emit':
        sys.stdout.write(emit(parts) + '\n')
    elif len(sys.argv) > 2 and sys.argv[1] == 'preview':
        os.makedirs(sys.argv[2], exist_ok=True)
        for name, im in parts:
            bg = np.zeros(im.shape[:2] + (3,), np.uint8); bg[:] = (30, 36, 62)
            al = im[..., 3:4] / 255.0
            comp = (im[..., :3] * al + bg * (1 - al)).astype(np.uint8)
            Image.fromarray(comp).resize((im.shape[1] * 4, im.shape[0] * 4), Image.NEAREST).save(os.path.join(sys.argv[2], name.lower() + '.png'))
    else:
        print(__doc__)


if __name__ == '__main__':
    main()
