# The user's tree sheet (reference/trees_user.webp), cut into its 11 trees and reduced by an exact integer factor
# (block kept if at least half opaque, colour = mean of the opaque pixels, palette shared), emitted for levelgen.cpp:placeTree:
#   python tools/trees_user.py > sprites_trees.h
import sys, os
import numpy as np
from PIL import Image
from scipy import ndimage

F = 6
SRC = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'reference', 'trees_user.webp')
ALPHA = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789+-'
im = np.array(Image.open(SRC).convert('RGBA'))
op = im[..., 3] > 40
lab, n = ndimage.label(ndimage.binary_dilation(op, iterations=6))  # the grass tufts and loose twigs stay with their tree
boxes = [b for b in ndimage.find_objects(lab) if (b[0].stop - b[0].start) * (b[1].stop - b[1].start) > 2000]
rows = sorted(boxes, key=lambda b: ((b[0].start + b[0].stop) // 2 > 500) * 10000 + b[1].start)  # top row then bottom row, left to right
assert len(rows) == 11, len(rows)
sprites = []
for b in rows:
    sub = im[b]
    h, w = (sub.shape[0] // F) * F, (sub.shape[1] // F) * F
    h0 = sub.shape[0] - h  # trim from the top so the feet stay on a block edge
    sub = sub[h0:h0 + h, :w]
    blk = sub.reshape(h // F, F, w // F, F, 4).transpose(0, 2, 1, 3, 4).reshape(h // F, w // F, F * F, 4)
    a = (blk[..., 3] > 40)
    cov = a.mean(-1)
    rgb = (blk[..., :3] * a[..., None]).sum(2) / np.maximum(a.sum(-1), 1)[..., None]
    sprites.append((cov >= 0.5, rgb))
allc = np.concatenate([s[1][s[0]] for s in sprites]).astype(np.uint8)
pal = Image.fromarray(allc.reshape(1, -1, 3)).quantize(len(ALPHA), method=Image.Quantize.MEDIANCUT, dither=Image.Dither.NONE)
pc = np.array(pal.getpalette()[:len(ALPHA) * 3]).reshape(-1, 3)
out = ['// Generated by tools/trees_user.py from the user\'s tree sheet - do not edit by hand', '#pragma once', '',
       'struct TreeSprite { int w, h; const char* px; };',
       'static const unsigned char TREE_PAL[%d][3] = {%s};' % (len(pc), ', '.join('{%d,%d,%d}' % tuple(c) for c in pc)),
       'static const char* const TREE_ALPHABET = "%s";' % ALPHA[:len(pc)], 'static const TreeSprite TREE_SPR[] = {']
for m, rgb in sprites:
    idx = np.abs(rgb[..., None, :] - pc[None, None]).sum(-1).argmin(-1)
    lines = [''.join(ALPHA[idx[y, x]] if m[y, x] else '.' for x in range(m.shape[1])) for y in range(m.shape[0])]
    out.append('    {%d, %d,\n%s},' % (m.shape[1], m.shape[0], '\n'.join('     "%s"' % l for l in lines)))
out.append('};')
print('\n'.join(out))
print('sizes', [(m.shape[1], m.shape[0]) for m, _ in sprites], file=sys.stderr)
