# Weapon icons baked from the same 3D-primitive renderer as the Viking (tools/viking*.py), so a weapon on the ground, in the
# hotbar or in the hand of a corpse is the same object he swings.  python tools/weapons3d.py > sprites_weapons3d.h
# Each weapon type is baked at 16 angles (22.5 degrees apart, 0 = pointing right, clockwise) with the light held fixed; the
# game picks the nearest and never rotates a texture. Palette tag 1 = the weapon's metal, 2 = the staff gem.
import math, os, sys
import numpy as np
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import viking as VK
from viking import Canvas, Draw
from viking_char import draw_held

SW = 0.8            # reference units -> sprite pixels
THICK = 1.7         # icons are chunkier than the weapon as held (viking_char.draw_held's k)
N_ANG = 16
CW = 150            # canvas side
# game WeaponType order (game.h): dagger sword axe crossbow staff armour spear mace pan
TYPES = ['dagger', 'sword', 'axe', 'crossbow', 'staff', None, 'spear', 'mace', 'pan']

PAL, PAL_LIST = {}, []


def pal_index(r, g, b, a, tag):
    k = (int(r), int(g), int(b), int(a), int(tag))
    if k not in PAL:
        PAL[k] = len(PAL_LIST); PAL_LIST.append(k)
    return PAL[k]


def held(t, ang):
    # a short grip so the weapon reads from the hand outward; the staff and the spear are held further down
    g = {'staff': (0, 0), 'spear': (0, 0)}.get(t, (0, 0))
    return dict(type=t, g=g, ang=ang, zg=6.0, zh=6.0)


def bake(t, k):
    cv = Canvas(CW, CW, CW // 2, SW)
    d = Draw(cv, CW // 2, 1, SW)
    draw_held(d, held(t, k * 360.0 / N_ANG), THICK)
    rgb, tag, op = cv.render(rim_side=1, floor_clip=False)
    ys, xs = np.where(op)
    x0, x1, y0, y1 = xs.min(), xs.max() + 1, ys.min(), ys.max() + 1
    idx = np.zeros((y1 - y0, x1 - x0), int)
    for y in range(y0, y1):
        for x in range(x0, x1):
            if op[y, x]: idx[y - y0, x - x0] = 1 + pal_index(*rgb[y, x], 255, tag[y, x])
    return idx, CW // 2 - x0, CW // 2 - y0


def rle(grid):
    flat = grid.reshape(-1)
    out, i = [], 0
    while i < len(flat):
        v, n = flat[i], 1
        while i + n < len(flat) and flat[i + n] == v and n < 255: n += 1
        out += [int(v), n]
        i += n
    return out


def emit():
    out = ['// Generated by tools/weapons3d.py - edit there, then: python tools/weapons3d.py > sprites_weapons3d.h',
           '#pragma once', '#include <raylib.h>', '',
           '// Weapon icons from the 3D renderer: per type, 16 angles (22.5 degrees apart, 0 = right, clockwise). pivot = the grip in the sprite.',
           'struct W3Type { const int* w; const int* h; const int* px; const int* py; const int* off; const unsigned char* rle; };', '']
    body, decl = [], []
    for ti, t in enumerate(TYPES):
        if t is None:
            decl.append('{nullptr, nullptr, nullptr, nullptr, nullptr, nullptr}')
            continue
        ws, hs, pxs, pys, offs, data = [], [], [], [], [], []
        for k in range(N_ANG):
            idx, px, py = bake(t, k)
            ws.append(idx.shape[1]); hs.append(idx.shape[0]); pxs.append(int(px)); pys.append(int(py)); offs.append(len(data))
            data += rle(idx)
        N = t.upper()
        body.append(f'static const int W3W_{N}[] = {{{",".join(map(str, ws))}}};')
        body.append(f'static const int W3H_{N}[] = {{{",".join(map(str, hs))}}};')
        body.append(f'static const int W3X_{N}[] = {{{",".join(map(str, pxs))}}};')
        body.append(f'static const int W3Y_{N}[] = {{{",".join(map(str, pys))}}};')
        body.append(f'static const int W3O_{N}[] = {{{",".join(map(str, offs))}}};')
        body.append(f'static const unsigned char W3D_{N}[] = {{{",".join(map(str, data))}}};')
        decl.append(f'{{W3W_{N}, W3H_{N}, W3X_{N}, W3Y_{N}, W3O_{N}, W3D_{N}}}')
        print(t, f'{max(ws)}x{max(hs)}', len(data), file=sys.stderr)
    out.append('static const Color W3_PAL[] = {{0, 0, 0, 0}, ' + ', '.join(f'{{{r}, {g}, {b}, {a}}}' for r, g, b, a, t in PAL_LIST) + '};')
    out.append('static const unsigned char W3_TAG[] = {0, ' + ', '.join(str(t) for r, g, b, a, t in PAL_LIST) + '};')
    out.append('')
    out += body
    out.append('')
    out.append('static const W3Type W3[] = {' + ',\n    '.join(decl) + '};')
    out.append('const int W3_ANGLES = 16;')
    return '\n'.join(out) + '\n'


def preview(path, z=4):
    from PIL import Image
    cells = []
    for t in TYPES:
        if t is None: continue
        row = []
        for k in range(N_ANG):
            idx, px, py = bake(t, k)
            im = Image.new('RGB', (CW // 2, CW // 2), (30, 24, 40))
            p = im.load()
            for y in range(idx.shape[0]):
                for x in range(idx.shape[1]):
                    v = idx[y, x]
                    if v:
                        r, g, b, a, tg = PAL_LIST[v - 1]
                        xx, yy = x + CW // 4 - px, y + CW // 4 - py
                        if 0 <= xx < CW // 2 and 0 <= yy < CW // 2: p[xx, yy] = (r, g, b)
            row.append(im)
        cells.append(row)
    sheet = Image.new('RGB', (N_ANG * CW // 2, len(cells) * CW // 2), (30, 24, 40))
    for r, row in enumerate(cells):
        for c, im in enumerate(row): sheet.paste(im, (c * CW // 2, r * CW // 2))
    sheet.resize((sheet.width * z // 4, sheet.height * z // 4), Image.NEAREST).save(path)


if __name__ == '__main__':
    if len(sys.argv) > 2 and sys.argv[1] == 'preview': preview(sys.argv[2])
    else: sys.stdout.write(emit())
